name: dart_polisher
description: >-
  Customizable Dart source code formatter. Forked from dart_style.
  Provides a CLI tool.
version: 0.9.4-dev
issue_tracker: https://github.com/xnfo-dart/dart_polisher/issues
repository: https://github.com/xnfo-dart/dart_polisher
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: '>=5.6.0 <=5.6.0'
  args: ^2.3.1
  dart_style: ^2.2.4
  path: ^1.8.2
  source_span: ^1.4.0
  pub_semver: ^2.1.1

dev_dependencies:
  grinder: ^0.9.2
  js: ^0.6.0
  lints: ^2.0.0
  node_preamble: ^2.0.1
  package_config: ^2.1.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  yaml: ">=2.0.0 <4.0.0"

executables:
  dartpolish: format
